name: luke
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchani
  - ase
  - rdkit
  - numpy
  - pandas
  - tqdm
  - scipy
  - openbabel
  - pip
  - pip:
      - -e .