name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            setup.py
            pyproject.toml
      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'requirements.txt', 'setup.py') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Cache torch & pip wheels (extras)
        id: cache-torch
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/torch
          key: piptorch-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'requirements.txt', 'setup.py') }}
          restore-keys: |
            piptorch-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Show cache key context
        run: |
          echo "Using pip cache based on requirements.txt, setup.py, pyproject.toml"
          echo "Venv cache hit: ${{ steps.cache-venv.outputs.cache-hit }}"
          echo "Torch/pip cache hit: ${{ steps.cache-torch.outputs.cache-hit }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Create venv if not present (cache may have restored it already)
          if [ ! -d .venv ]; then
            python -m venv .venv
          fi
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          . .venv/bin/activate
          pip install --upgrade pip
          # Always install with deps to avoid missing packages on stale cache
          pip install -e .[dev,chem]
      - name: Verify environment
        run: |
          . .venv/bin/activate
          python -V
          python -c "import torch, torchani; print('torch', torch.__version__, 'torchani', torchani.__version__)"
          pip list | grep -E 'torch|torchani|ruff' || true
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check luke tests
      - name: Test (LUKE only)
        run: |
          . .venv/bin/activate
          pytest -q --maxfail=1 --disable-warnings tests
      - name: Build (sdist/wheel) smoke
        run: |
          . .venv/bin/activate
          pip install build
          python -m build --sdist --wheel --outdir dist
      - name: Twine check
        run: |
          . .venv/bin/activate
          pip install twine
          twine check dist/*